sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fortsite/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true fortsite/docker-react npm run test
